Implemented support for Indices
JavaWebStack/ORM pull request #43
Opened 2023-03-30 16:03 UTC by x7airworker

This will fix #42.

2023-03-31 08:56 UTC, JanHolger requested changes

2023-03-31 08:56 UTC, JanHolger commented on src/main/java/org/javawebstack/orm/annotation/Indices.java
> +public @interface Indices {
Move into Index as a subclass since it's not used anywhere

2023-03-31 08:56 UTC, JanHolger commented on src/main/java/org/javawebstack/orm/migration/AutoMigrator.java
> +import jdk.internal.joptsimple.internal.Strings;
Remove import of jdk internals

2023-04-20 12:32 UTC, JanHolger requested changes
Please implement a test for it

2023-04-21 09:48 UTC, x7airworker commented
I've added tests and the code is ready for review!

2023-04-27 12:36 UTC, JanHolger approved these changes

2023-04-27 12:37 UTC, merged